### ISSUE TITLE
[Bug]: Custom Resource Classes Config excerpt is incomplete

### ISSUE THREAD

**Issue by StarrrLiteNL** [tomatophp/filament-users#23]
### What happened?

After upgrading to 2.0.8 I added the config exceprt from the github page yo my config but was met with an error when trying to view a user.

### How to reproduce the bug

* Install 2.0.8
* Add the excerpt to your config 
* Go to the users list
* Try to view a user

### Package Version

2.0.8

### PHP Version

8.3.4

### Laravel Version

v11.29.0

### Notes

Adding 
`'view' => \TomatoPHP\FilamentUsers\Resources\UserResource\Actions\ViewPageActions::class,`
to the config file in the pages section solved the issue.
All that needs to happen is to update the documentation :)

**Comment by 3x1io** [comment]
thanks @StarrrLiteNL it's working now on the last version v2.0.9
