### ISSUE TITLE
Error occured when editing users

### ISSUE THREAD

**Issue by DrewNeon** [tomatophp/filament-users#4]
First of all, thanks for making such a useful package!

The installation was very smooth, and the `Users` item showed up immediately after refreshing the dashboard. However, after publishing the rersource via `php artisan filament-users:publish`, a duplicated item with some sort of raw name appeared as shown in the following screenshot.

<img width="360" alt="image" src="https://github.com/tomatophp/filament-users/assets/25809783/65b7a2ff-b1fb-4b9f-bc43-030e06b5abc8">

Clicking either of them will route to `/admin/users`, and shows the same user list. I also tried to edit one user. When clicking the "Save Change" button while leaving the `password` field blank, it threw an error message `Property [password] does not exist on this collection instance.`

Enviroment Info
```
PHP version: 8.2.13
Laravel version: 10.37.3
Filament version: 3.1.23
```

**Comment by DrewNeon** [comment]
I found out the reason of duplicated menu items, I forgot to change the config. However, after changing the `publish_resource` to `true`, the odd-named item remains.

<img width="360" alt="image" src="https://github.com/tomatophp/filament-users/assets/25809783/de16b601-be1c-49a2-92f2-08c3cd81790e">

**Comment by DrewNeon** [comment]
> I found out the reason of duplicated menu items, I forgot to change the config. However, after changing the `publish_resource` to `true`, the odd-named item remains.
> 
> <img alt="image" width="360" src="https://private-user-images.githubusercontent.com/25809783/292203119-de16b601-be1c-49a2-92f2-08c3cd81790e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMTY1NzQsIm5iZiI6MTcwMzIxNjI3NCwicGF0aCI6Ii8yNTgwOTc4My8yOTIyMDMxMTktZGUxNmI2MDEtYmUxYy00OWEyLTkyZjItMDhjM2NkODE3OTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAzMzc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYmRiZmFlZWQ5ODQ4NjNhZTJkZjk5YmFiMGIyNzAwYzQ1ODA3M2NjMTlhNTgzZDBiM2NmNzdlNTMxZGJlMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rqr3jd3MyyMJ77b6IY_5wcZgmX0fEDhgYh_SRpw809k">

I've figured this issue out, it's caused by spelling mistakes. Please replace all `trans('filament-user::xxx')` within resource files with `trans('filament-users::xxx')`.

Couldn't solve the `Property [password] does not exist on this collection instance.` error message when saving changes on user edit page yet.

**Comment by 3x1io** [comment]
fixed on https://github.com/tomatophp/filament-users/releases/tag/v1.0.4
