### ISSUE TITLE
can't find filament-user.php

### ISSUE THREAD

**Issue by breizhwave** [tomatophp/filament-users#8]
Hi, successfully installed your panel, but seems filament-user was not created... well I created that manually and it works, may be you should specify this in readme

and after I have configured successfully roles and users,  some / resources still appear in the menu even though permissions not checked... any idea ?

**Comment by victorelec14** [comment]
Hi, the step is at the end of the document. I just created an MR adding the missing step.

You can publish the assets with this command.

> php artisan vendor:publish --tag="filament-users-config"

Regards

**Comment by 3x1io** [comment]
@victorelec14 thanks for your support and help
